### ISSUE TITLE
getLayoutById() is null

### ISSUE THREAD

**Issue by clarknelson** [ethercreative/splash#8]
After installing the plugin I get this message:

```
2019-03-27 09:09:03 [-][1][b9bjju5ps0886ji1apuk1assf2][error][TypeError] TypeError: Argument 1 passed to craft\services\Fields::getLayoutById() must be of the type integer, null given, called in /Users/clarknelson/Documents/lse/vendor/ether/splash/src/Splash.php on line 79 and defined in /Users/clarknelson/Documents/lse/vendor/craftcms/cms/src/services/Fields.php:974
Stack trace:
#0 /Users/clarknelson/Documents/lse/vendor/ether/splash/src/Splash.php(79): craft\services\Fields->getLayoutById(NULL)
#1 /Users/clarknelson/Documents/lse/vendor/craftcms/cms/src/base/Plugin.php(224): ether\splash\Splash->settingsHtml()
#2 /Users/clarknelson/Documents/lse/vendor/craftcms/cms/src/controllers/PluginsController.php(117): craft\base\Plugin->getSettingsResponse()
#3 [internal function]: craft\controllers\PluginsController->actionEditPluginSettings('splash', Object(ether\splash\Splash))
#4 /Users/clarknelson/Documents/lse/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#5 /Users/clarknelson/Documents/lse/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#6 /Users/clarknelson/Documents/lse/vendor/craftcms/cms/src/web/Controller.php(109): yii\base\Controller->runAction('edit-plugin-set...', Array)
#7 /Users/clarknelson/Documents/lse/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('edit-plugin-set...', Array)
#8 /Users/clarknelson/Documents/lse/vendor/craftcms/cms/src/web/Application.php(297): yii\base\Module->runAction('plugins/edit-pl...', Array)
#9 /Users/clarknelson/Documents/lse/vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction('plugins/edit-pl...', Array)
#10 /Users/clarknelson/Documents/lse/vendor/craftcms/cms/src/web/Application.php(286): yii\web\Application->handleRequest(Object(craft\web\Request))
#11 /Users/clarknelson/Documents/lse/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#12 /Users/clarknelson/Documents/lse/web/index.php(21): yii\base\Application->run()
#13 /Users/clarknelson/.composer/vendor/laravel/valet/server.php(158): require('/Users/clarknel...')
#14 {main}
```

**Comment by angrybrad** [comment]
The bug is here, assuming that a Volume will always have a fieldLayoutId, when it would be null if there are no fields assigned to it: https://github.com/ethercreative/splash/blob/v3/src/Splash.php#L79
